Update DNX
We're now using packages with generations. The version of DNX that is
currently being used doesn't know about generations which causes the
it to resolve against implementation assemblies. That causes weird
compilation errors such as

  error CS0731: The type forwarder for type 'System.Diagnostics.CodeAnalysis.SuppressMessageAttribute' in assembly 'mscorlib' causes a cycle

This updates DNX to RC1.