Fix parsing bug
There is currently a bug in the parser that causes this code:

  -f -f

to not be parsed correctly. Instead of simply getting the flag f to be set
to true, the app gives the error:

  error: invalid option -f

The root cause is that the parser advances tokens when it shouldn't.